language: java 
before_install:
  - openssl aes-256-cbc -K $encrypted_5880cf525281_key -iv $encrypted_5880cf525281_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
script:
- ./gradlew check
deploy:
  provider: gae
  keyfile: springboot22-09d2ded0aca3.json
  project: springboot22